include: "rules/common.smk"


if lookup(dpath="load_fair_genome_indexer_pipeline", within=config):

    include: "rules/fair_genome_indexer_pipeline.smk"


if lookup(dpath="load_fair_bowtie2_mapping_pipeline", within=config):

    include: "rules/fair_bowtie2_mapping_pipeline.smk"


if lookup(dpath="load_fair_fastqc_multiqc_pipeline", within=config):

    include: "rules/fair_fastqc_multiqc_pipeline.smk"


include: "rules/bcftools.smk"
include: "rules/gatk_mutect2_calling_meta.smk"
include: "rules/gatk.smk"
include: "rules/multiqc.smk"


rule fair_cnv_facets_targets:
    input:
        unpack(get_fair_cnv_facets_targets_targets),
    output:
        touch("tmp/targets/fair_cnv_facets_targets.txt"),
    log:
        "logs/fair_cnv_facets_targets.log",
    benchmark:
        "benchmark/fair_cnv_facets_targets.tsv"
